#!/bin/bash

# Empty the macOS trash
echo -n "Are you sure you want to empty the trash? [y/N] "
read -r response

if [[ "$response" =~ ^[Yy]$ ]]; then
    osascript -e 'tell application "Finder" to empty trash'
    echo "Trash emptied"
else
    echo "Cancelled"
fi